#ifndef GAMMATRANSFORM_GLOBAL_H
#define GAMMATRANSFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAMMATRANSFORM_LIBRARY)
#  define GAMMATRANSFORMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GAMMATRANSFORMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GAMMATRANSFORM_GLOBAL_H
