#ifndef MATDISPLAYER_GLOBAL_H
#define MATDISPLAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MATDISPLAYER_LIBRARY)
#  define MATDISPLAYERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MATDISPLAYERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MATDISPLAYER_GLOBAL_H
