#ifndef AXTOBTHPLUSC_GLOBAL_H
#define AXTOBTHPLUSC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AXTOBTHPLUSC_LIBRARY)
#  define AXTOBTHPLUSCSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AXTOBTHPLUSCSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AXTOBTHPLUSC_GLOBAL_H
