#ifndef MATTOTYPE8U_GLOBAL_H
#define MATTOTYPE8U_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MATTOTYPE8U_LIBRARY)
#  define MATTOTYPE8USHARED_EXPORT Q_DECL_EXPORT
#else
#  define MATTOTYPE8USHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MATTOTYPE8U_GLOBAL_H
