#ifndef LOOPCONTROL_GLOBAL_H
#define LOOPCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOOPCONTROL_LIBRARY)
#  define LOOPCONTROLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOOPCONTROLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LOOPCONTROL_GLOBAL_H
