#ifndef THREEDTOMAT_GLOBAL_H
#define THREEDTOMAT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THREEDTOMAT_LIBRARY)
#  define THREEDTOMATSHARED_EXPORT Q_DECL_EXPORT
#else
#  define THREEDTOMATSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // THREEDTOMAT_GLOBAL_H
