#ifndef PCIMAGEMASK_GLOBAL_H
#define PCIMAGEMASK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PCIMAGEMASK_LIBRARY)
#  define PCIMAGEMASKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PCIMAGEMASKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PCIMAGEMASK_GLOBAL_H
