#ifndef BLOBCLUSTER_GLOBAL_H
#define BLOBCLUSTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BLOBCLUSTER_LIBRARY)
#  define BLOBCLUSTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BLOBCLUSTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BLOBCLUSTER_GLOBAL_H
