#ifndef PCSERIALIZER_GLOBAL_H
#define PCSERIALIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PCSERIALIZER_LIBRARY)
#  define PCSERIALIZERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PCSERIALIZERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PCSERIALIZER_GLOBAL_H
