#ifndef TARGET_NAME_AUTO_REPLACED_GLOBAL_H
#define TARGET_NAME_AUTO_REPLACED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TARGET_NAME_AUTO_REPLACED_LIBRARY)
#  define TARGET_NAME_AUTO_REPLACEDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TARGET_NAME_AUTO_REPLACEDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TARGET_NAME_AUTO_REPLACED_GLOBAL_H
