#ifndef AABOUNDINGBOX_GLOBAL_H
#define AABOUNDINGBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AABOUNDINGBOX_LIBRARY)
#  define AABOUNDINGBOXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AABOUNDINGBOXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AABOUNDINGBOX_GLOBAL_H
