#ifndef GRAYCONVERTER_GLOBAL_H
#define GRAYCONVERTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAYCONVERTER_LIBRARY)
#  define GRAYCONVERTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GRAYCONVERTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAYCONVERTER_GLOBAL_H
