#ifndef SPACIALCLUSTER_GLOBAL_H
#define SPACIALCLUSTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SPACIALCLUSTER_LIBRARY)
#  define SPACIALCLUSTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SPACIALCLUSTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SPACIALCLUSTER_GLOBAL_H
