#ifndef MATTHRESHOLD_GLOBAL_H
#define MATTHRESHOLD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MATTHRESHOLD_LIBRARY)
#  define MATTHRESHOLDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MATTHRESHOLDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MATTHRESHOLD_GLOBAL_H
